### ISSUE TITLE
Need help Higher/Lower Strategy with Stochastic RSI

### ISSUE THREAD

**Issue by Onesmus-Nzoka** [binary-ex-machina/binaryblocks#11]
Hello Sir,
I hope this finds you well.
Please help me set up this strategy in a bot on binaryblocks.pro platform.
When Stochastic RSI is 1 and stays at 1 for 2 ticks purchase Higher and when Stochastic RSI is 0 and stays for 2 ticks.
The barriers are -0.25 and +0.25. I have been trading manually and I was wondering if I can apply it on a bot.
Attached is screenshot from the webtrader.
Thanks in advance.
![Stochastic RSI strategy](https://user-images.githubusercontent.com/106060475/220865113-6688f772-b786-4bc1-9d27-8186314a8875.jpg)

**Comment by binary-ex-machina** [comment]
@Onesmus-Nzoka, unfortunately, it's not possible to reproduce that indicator using the blocks. It uses a specific calculation, very different from the formula of the Stochastic RSI original indicator. The original indicator will use one value and has four inputs. Since the indicator you suggested using one, I can't help you with that. 

You can use this page https://tradingview.binary.com/ to check what indicators can be used. Also, the indicators from https://app.deriv.com/ can be reproduced or are already in the Binary blocks.

![image](https://user-images.githubusercontent.com/34610787/221273956-47d26af7-50cc-400a-a12c-11fdb11a6530.png)
